server.name: kibana
server.host: "192.168.4.1"
elasticsearch.url: http://192.168.4.1:9200
elasticsearch.username: elastic
elasticsearch.password: changeme
xpack.monitoring.ui.container.elasticsearch.enabled: true
